#!/usr/bin/env bash

#set -u # default /lib/gentoo/functions.sh makes use of unbound variables :(

declare DEFAULT_API="https://api.gentoo.org"

main() {
	local repository_name="${1:-}"
	#local sync_uri="${2:-}"
	local repository_path="${3:-}"

	if ! [[ -n "${repository_name:-}" && -n "${repository_path}" ]]; then
		eerror "Invalid '${0}' parameters: '${*:-}'"
		return 1
	fi

	[[ "${repository_name:-}" == "gentoo" ]] || return 0

	source /lib/gentoo/functions.sh || return 1

	ebegin "Updating 'projects.xml' for repo '${repository_name}'"
	# TODO: Parse ${FETCHCOMMAND} to identify command to use to perform download?
	wget -qN "${DEFAULT_API}"/metastructure/projects.xml -P "${repository_path}"/metadata/
	eend ${?}
} # main

main "${@:-}"

exit ${?}
