#!/usr/bin/env bash

#set -u # default /lib/gentoo/functions.sh makes use of unbound variables :(

declare DEFAULT_GIT="https://anongit.gentoo.org/git"

main() {
	local repository_name="${1:-}"
	#local sync_uri="${2:-}"
	local repository_path="${3:-}"

	local dtddir="${repository_path}"/metadata/dtd

	if ! [[ -n "${repository_name:-}" && -n "${repository_path}" ]]; then
		eerror "Invalid '${0}' parameters: '${*:-}'"
		return 1
	fi

	[[ "${repository_name:-}" == "gentoo" ]] || return 0

	source /lib/gentoo/functions.sh || return 1

	ebegin "Updating DTDs for repo '${repository_name}'"
	if [[ -d "${dtddir}" ]]; then
		git -C "${dtddir}" pull -q --ff-only
	else
		git clone -q "${DEFAULT_GIT}"/data/dtd.git "${dtddir}"
	fi
	eend ${?}
} # main

main "${@:-}"

exit ${?}
