#!/usr/bin/env bash

#set -u # default /lib/gentoo/functions.sh makes use of unbound variables :(

main() {
	local repository_name="${1:-}"
	#local sync_uri="${2:-}"
	local repository_path="${3:-}"

	local -i parallel_jobs=1
	local opts=''

	if ! [[ -n "${repository_name:-}" ]]; then
		eerror "Invalid '${0}' parameters: '${*:-}'"
		return 1
	fi

	[[ "${repository_name:-}" == "gentoo" ]] && return 0

	source /lib/gentoo/functions.sh || return 1

	# Number of jobs for egencache, default is number of processor cores.
	parallel_jobs="$( nproc >/dev/null 2>&1 || echo '1' )"

	if [[ -n "${repository_path}" && -d "${repository_path}" ]]; then
		if [[ -s "${repository_path}"/profiles/use.local.desc ]]; then
			opts='--preserve-comments'
		fi
	fi

	ebegin "Updating metadata cache for overlay repo '${repository_name}'"
	# shellcheck disable=SC2086
	egencache --jobs=${parallel_jobs} --repo="${repository_name}" --update --update-use-local-desc ${opts:-}
	eend ${?}
} # main

main "${@:-}"

exit ${?}
